version: '3.8'
services: 
  web:
    image: nginx:alpine
    restart: unless-stopped
    ports: 
      - "8080:8000"
    volumes: 
      - ./:/var/www
      - ./.docker/nginx.conf:/etc/nginx/conf.d/nginx.conf

  app:
    build:
      context: .
      dockerfile: ./.docker/app.dockerfile
    volumes: 
      - ./:/var/www
      


