monolog:
    handlers:
        blog:
            type: stream
            path: "%kernel.logs_dir%/blog_channel_%kernel.environment%.log"
            level: debug
            channels: ['blog_channel']
        main:
            type: stream                                        #The logs will be stored inside files
            path: "%kernel.logs_dir%/%kernel.environment%.log"  # where those files should be stored
            level: debug
            channels: ["!event", "!blog_channel"]               #which types of messages you would like to store.
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
